### ISSUE TITLE
Is there a Mendix 6 version?

### ISSUE THREAD

**Issue by simo101** [appronto/UXManipulator#1]
I started working on a Mendix 6 version but it doesn't work 100% when i change a page. The first page it will work but when i go onto another page it fails to work. Here is my upgrade:
[https://github.com/simo101/UXManipulator](https://github.com/simo101/UXManipulator)

Hopefully it is of use.

**Comment by Aelion-MM** [comment]
Doesn't work at all in MX 6.10.9 any plans to update the widget?

**Comment by pimvdnoll** [comment]
Hi Mitchel. No plans to update this widget for mx6 or 7. There is a similar widget for setting attributes on a node. Take a look at https://appstore.home.mendix.com/link/app/5958/TimeSeries/Set-Attribute
